---
title: "Introdução à Ciência dos Dados - 2023"
subtitle: "Mestrado Profissional em Admministração (IFMG - Campus Formiga)"
lang: "pt"
author: "Prof. Washington Santos da Silva"
format:
  pdf:
    number-sections: true
    colorlinks: true
---


## Logística

Ambiente Virtual de Aprendizagem: \url{https://ead.ifmg.edu.br/formiga/} 

Local das Aulas: **Laboratório de Informática 2 - Bloco B - 2 Andar**

Dia/Horário: **Quinta-Feira: 18:30 - 22:30**


## Objetivo Geral

Capacitar os mestrandos na aplicação de modelos econométricos a 
problemas de áreas de finanças. O conteúdo principal do curso concentra-se na 
aquisição e estruturação de dados, análise exploratória de dados, visualização 
de dados, modelagem estatística e econométrica e comunicação eficaz de resultados, utilizando-se a linguagem R. Trata-se de um curso do tipo 
"hands-on". O objetivo do curso é levar os mestrandos do zero à capacidade de trabalhar em um projeto econométrico-computacional **reproduzível** usando a linguagem R, analisando um conjunto de dados para respondenr à questões de interesse científico.


## Objetivos específicos

1. Tornar o mestrando em um usuário da linguagem R para a importação, 
   organização, visualização e modelagem econométrica de dados;

3. Introduzir o mestrando na aplicação de modelos econométricos na área de 
   finanças;

2. Tornar o mestrando capacitado para o desenvolvimento de pesquisas 
   empíricas reproduzíveis na área de finanças;


## Pré-Requisitos

Não há pré-requisitos formais. Será importante rever conceitos matemáticos, 
de estatística básica conforme necessário, sendo importante que os mestrandos se envolvam no domínio de conceitos básicos ativamente. Algum letramento 
computacional também será muito importante. Além disso, curiosidade, pensamento analítico e determinação são competências pessoais fundamentais para a 
disciplina, e para qualquer aspirante a pesquisador.

 
## Políticas do Curso

Use as informações abaixo como referência sobre como o curso será conduzido. 
Analise essas informações atentamente antes de entrar em contato com 
alguma dúvida. 


### Avaliações

1) Lista de Exercícios 1 realizada pelo Ambiente Virtual de Aprendizagem = 10 pontos

2) Lista de Exercícios 2 realizada pelo Ambiente Virtual de Aprendizagem = 10 pontos

3) Ensaio sobre 4 artigos o qual deverá ser enviado pelo Ambiente Virtual de Aprendizagem = 10 pontos. Os artigos são:

    - HARKNESS, T. \href{https://doi.org/10.1111/1740-9713.01504}{The history of       the data economy: Part I: The birth of customer insight}. Significance, v. 
      18, n. 2, p. 12–15, a2021.

    - HARKNESS, T. \href{https://doi.org/10.1111/1740-9713.01547}{The history of 
      the data economy: Part II: Analytics arrives}. Significance, v. 18, n. 4,  
      p. 16–19, b2021.

    - HARKNESS, T. \href{https://doi.org/10.1111/1740-9713.01567} {The history of       the data economy: Part III: The new kings and queens of data}. 
      Significance, v. 18, n. 5, p. 16–19, c2021.

    - HARKNESS, T. \href{https://doi.org/10.1111/1740-9713.01586}{The history of       the data economy: Part IV: The future}. Significance, v. 18, n. 6, p. 
      12–15, d2021.

4) Exame intermediário presencial = 35 pontos

5) Exame Final presencial = 35 pontos

Para aprovação na disciplina é necessária a obtenção de pelo menos 
60 pontos.


### Comunicação e Ambiente Virtual de Aprendizagem

Após a liberação do acesso à sala virtual da disciplina no Ambiente Virtural de 
Aprendizagem do IFMG (Moodle), nossa comunicação será realizada prioritariamente 
por esta sala virtual.


### Honestidade Acadêmica

O plágio mina o próprio cerne da missão desta disciplina, que é que cada 
mestrando cresça como um acadêmico emergente em pesquisas empíricas na área de 
concentração do curso. Sem buscar completar todas as atividades de 
forma autonôma, você nunca será capaz de atingir um nível de proficiência 
adequado para um aspirante a pesquisador. Pior ainda, o plágio reduz a confiança mútua no trabalho, um componente necessário do empreendimento científico.

O plágio inclui a cópia no todo ou em parte de trabalhos acadêmicos publicados 
anteriormente sem a devida citação, mas também abrange fazer com que o trabalho 
de outra pessoa seja seu, independentemente de ter sido publicado ou não. 

Contratar alguém para escrever um ensaio para você é tão plágio quanto se você 
copiasse um artigo existente para o seu trabalho. Se houver evidência 
consistente de que um mestrando voluntariamente plagiou uma tarefa, será 
atribuída a nota zero na tarefa, sendo que o envolvido poderá ser 
reprovado na disciplina e receber outras medidas disciplinares de acordo com 
as normas institucionais aplicáveis.


## Referências Bibliográficas

*Referências principais*:

BROOKS, Chris. (2019). **Introductory Econometrics for Finance**. 4 ed.
Cambridge University Press.

WICKHAM Hadley; GROLEMUND, Garrett. (2023). **R for data science. import, tidy, transform, visualize, and model data**. 2nd. ed. O’Reilly Media, Inc. 
Disponível em: \url{https://r4ds.hadley.nz}.


*Referências Complementares*:

WOOLDRIDGE, Jeffrey M. **Introdução à econometria: uma abordagem moderna**. 
São Paulo: Thomson, 2006.

JAMES, G.; WITTEN, D.; HASTIE, T. & TIBSHRANI, R. **An introduction to statistical learning**. 2nd. edition. New York: Springer, 2021. Disponível em: \url{https://www.statlearning.com/}


## Cronograma

- Aula 1 - 09/03

    - Apresentação do Programa da Disciplina
    - Introdução à Linguagem R
    - Brooks (2019): Chapter 1

- Aula 2 - 23/03

    - Fundamentos
    - Tipos de Dados
    - Brooks (2019): Chap. 2

- Aula 3 - 30/03

    - Fundamentos
    - Tipos de Dados
    - Brooks (2019): Chap. 2

- Aula 4 - 13/04  

    - Modelos de Regressão
    - Brooks (2019): Chaps. 3, 4.

- Aula 5 - 20/04

    - Modelos de Regressão
    - Brooks (2019): Chaps 3, 5

- Aula 6 - 27/04

    - Introdução a Modelos para Séries Temporais
    - Brooks (2019): Chap. 6

- Aula 7 - 04/05

    - Exame Intermediário

- Aula 8 - 11/05

    - Modelos para Dados em Painel
    - Brooks (2019): Chap. 11

- Aula 9 - 18/05 

    - Modelos para Dados em Painel
    - Brooks (2019): Chap. 11

- Aula 10 - 25/05

    - Modelos para Variáveis Dependentes Limitadas
    - Brooks (2019): Chap. 12

- Aula 11 - 01/06

    - Modelos para Variáveis Dependentes Limitadas
    - Brooks (2019): Chap. 12

- Aula 12 - 15/06

    - Exame Final

- Ensaio - Aula 16/03

    - Atividade no Ambiente Virtual de Aprendizagem 
    - Previsão de envio: até XX/XX/2023

- Lista de Exercícios 1 - Aula 22/06

    - Atividade no Ambiente Virtual de Aprendizagem 
    - Previsão de envio: até XX/XX/2023

- Lista de Exercícios 2 - Aula 29/06

    - Atividade no Ambiente Virtual de Aprendizagem
    - Previsão de envio: até XX/XX/20233

