---
title: "Aula06 - Introdução à Ciência dos Dados"
subtitle: "Escala de Likert"
author: "Seu Nome"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE}
# configuracoes globais
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      digits = 3, scipen = 999)

# pacotes utilizados
library(readr)
library(readxl)
library(plyr)
library(dplyr)
library(likert)
library(ggplot2)
library(scales) 
```




# Importando o arquivo de dados 

```{r}
path_rds <- "dados/dados_categoricos_analise.rds"
dados_questionario <- read_rds(path_rds)
glimpse(dados_questionario)
```


```{r}
dados_xlsx <- read_xlsx('dados/dados_categoricos_if.xlsx')
```

```{r}
dados_xlsx_quest <- dados_xlsx %>%
  transmute(
    q1_1 = factor(
      q1_1,
      levels = c(
        "20-30 anos",
        "31-40 anos",
        "41-50 anos",
        "51-60 anos",
        "Mais de 60 anos"
      ),
      ordered = TRUE
    ),
    q1_2 = factor(q1_2),
    q1_3 = factor(q1_3),
    q1_4 = factor(q1_4),
    q1_5 = factor(
      q1_5,
      levels =  c(
        "Ensino fundamental",
        "Ensino médio",
        "Ensino superior",
        "Especialização",
        "Mestrado",
        "Doutorado"
      ),
      ordered = TRUE
    ),
    q1_6 = factor(
      q1_6,
      levels = c(
        "Até 5 anos",
        "6-10 anos",
        "11-15 anos",
        "16-20 anos",
        "Mais de 20 anos"
      ),
      ordered = TRUE
    ),
    q1_7 = factor(
      q1_7,
      levels = c(
        "Até 5 anos",
        "6-10 anos",
        "11-15 anos",
        "16-20 anos",
        "Mais de 20 anos"
      ),
      ordered = TRUE
    ),
    q1_8 = factor(q1_8),
    q1_9 = factor(q1_9),
    q2_1 = factor(q2_1),
    q2_2 = factor(q2_2),
    q2_3 = factor(q2_3),
    q2_4 = factor(q2_4),
    q2_5 = factor(q2_5),
    q2_6 = factor(q2_6),
    q2_7 = factor(q2_7),
    q2_8 = factor(q2_8),
    q2_9 = factor(q2_9),
    q2_10 = factor(q2_10),
    q2_11 = factor(q2_11),
    q2_12 = factor(q2_12),
    q2_13 = factor(q2_13),
    q2_14 = factor(q2_14),
    q2_15 = factor(q2_15),
    q2_16 = factor(q2_16),
    q2_17 = factor(q2_17),
    q2_18 = factor(q2_18),
    q3_1 = factor(q3_1),
    q3_2 = factor(q3_2),
    q3_4 = factor(q3_4),
    q3_6 = factor(q3_6),
    q3_7 = factor(
      q3_7,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q3_8 = factor(
      q3_8,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q3_9 = factor(q3_9),
    q3_10 = factor(q3_10),
    q3_11 = factor(q3_11),
    q3_12 = factor(q3_12),
    q3_13 = factor(q3_13),
    q3_14 = factor(q3_14),
    q3_15 = factor(q3_15),
    q3_16 = factor(q3_16),
    q3_17 = factor(q3_17),
    q3_18 = factor(q3_18),
    q3_19 = factor(q3_19),
    q4_1 = factor(
      q4_1,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_2 = factor(
      q4_2,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_3 = factor(
      q4_3,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_4 = factor(
      q4_4,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_5 = factor(
      q4_5,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_6 = factor(
      q4_6,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_7 = factor(
      q4_7,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_8 = factor(
      q4_8,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_9 = factor(
      q4_9,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_10 = factor(
      q4_10,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_11 = factor(
      q4_11,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q4_12 = factor(
      q4_12,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
  q5_1 = factor(
      q5_1,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_2 = factor(
      q5_2,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_3 = factor(
      q5_3,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_4 = factor(
      q5_4,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_5 = factor(
      q5_5,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_6 = factor(
      q5_6,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_7 = factor(
      q5_7,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_8 = factor(
      q5_8,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_9 = factor(
      q5_9,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    ),
    q5_10 = factor(
      q5_10,
      levels = c(
        "Discordo totalmente", 
        "Discordo parcialmente", 
        "Nem concordo, nem discordo", 
        "Concordo parcialmente", 
        "Concordo totalmente"),
      ordered = TRUE
    )
)
```


```{r}
glimpse(dados_xlsx_quest)
```


# Grupo 3

```{r}
grupo3 <- dados_xlsx_quest %>% select(q3_7, q3_8)  
glimpse(grupo3)
```



```{r}
grupo3 <- grupo3 %>%
  rename( "Você concorda que existe contribuição
           dos auditores de órgãos de controle
           (TCU/CGU) para gerenciar os riscos da
            sua instituição?" = q3_7,
          "Você concorda que existe contribuição
           dos auditores internos para o processo
           de gestão de riscos da sua instituição?" = q3_8
        )

names(grupo3)
```


```{r}
grupo3 <- likert(grupo3)
```



```{r}
meus_niveis <- c("Discordo totalmente", "Discordo parcialmente", 
                 "Nem concordo, nem discordo", "Concordo parcialmente", 
                 "Concordo totalmente")

for(i in seq_along(grupo3)) {
  grupo3[,i] <- factor(grupo3[,i], levels = meus_niveis)
}

grupo3_likert <- likert(grupo3)
```

